# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Example function of rcpp
#'
#' @param string first string
#' @param string second string
#' @return list list of two vectors
#' @export
rcpp_hello_world <- function(a, b) {
    .Call('rcpphi_rcpp_hello_world', PACKAGE = 'rcpphi', a, b)
}

